name: ci

on:
  push:
    branches:
      - master

env:
  GO111MODULE: on

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.14
      - uses: actions/checkout@v3
      - run: make build
      - run: make test
